### ISSUE TITLE
Possible race condition in gRPC test?

### ISSUE THREAD

**Issue by ericbottard** [projectriff/function-sidecar#47]
Seeing this kind of logs when running tests:
```
2018/02/07 12:55:13 Error receiving message from function: rpc error: code = Unavailable desc = transport is closing
```

What's strange is that I manage to see between zero and seven instances of this message for one invocation of `make test`. The tests still pass.

**Comment by glyn** [comment]
With the Go/gRPC shell-function-invoker and the echo sample, I see the same message issued a large number of times when the pod is scaled back to 0. It seems that the function-sidecar is not terminating promptly and is in a tight spin encountering and printing the above error. It is not surprising the error is being encountered since the container hosting the gRPC server terminates promptly.
